### PR TITLE
Fix/ready transcripts

### LINKED ISSUE #1126: RSS could not publish, transcript with no format value
Not sure how, perhaps an issue on create, but we had a transcript with no format value, which then caused an issue calling to_sym on that nil format in the rss builder code.

So, 2 problems to fix here
 - why was the format set to nil?
 - update the builder to handle that nil, just in case

failed on this line of code
https://github.com/PRX/feeder.prx.org/blob/main/app/views/podcasts/show.rss.builder#L164C65-L164C71

partial stack trace
```
undefined method `to_sym' for nil
(eval at /app/app/models/feed_builder.rb:19):164:in `block (4 levels) in to_feed_xml'
```

and here was the transcript instance with the `nil` format:
```
#<Transcript:0x00007f8bff3a29c8
 id: 233,
 episode_id: 197697,
 status: "complete",
 guid: "76c0992e-9f34-4955-8bd4-930f7f098389",
 url: nil,
 original_url: "s3://infrastructure-cd-root-produc-feederuploadsbu...",
 mime_type: nil,
 file_size: 48417,
 format: nil,
 deleted_at: nil,
 created_at: "2024-10-07 21:03:40.214478000 +0000",
 updated_at: "2024-10-07 21:04:12.273804000 +0000">
```

Here's the slack thread looking into it:
https://prx.slack.com/archives/G0FKLK2Q5/p1728910632681439

### LINKED ISSUE #1127: Support plain text transcripts
looking into #1126, noticed that the producers uploaded plain text transcripts, but that was not a format option, so they picked html. The files are really just speaker identifiers and text, no timings, and no html, so it isn't correct to set them as html, but they didn't have a better option. 

I think we should add plain text as an option, it is listed in the podcast namespace docs for transcript tags as an acceptable option.

### PR DESCRIPTION
**Pull request by cavis**
Fixes #1126.  Fixes #1127.

Encountered an invalid transcript in prod (an uploaded mp3), which was getting rendered into the RSS.

This copies the "ready_media" / "ready_image" pattern to a new `ready_transcript` method.

Also adds text file support, and makes that the default.  The spec is kind of ambiguous if text is supported, but we have users uploading text, so may as well allow it.

### CODE REVIEW

File: app/models/episode.rb [hunk 1]
```diff
@@ -365,7 +365,7 @@ def validate_media_ready
     end
   end
 
-  def transcript?
-    transcript.present?
+  def ready_transcript
```
Comment (radical-ube) [inline app/models/episode.rb:368]: i feel like this just clicked a puzzle piece for me. i see this pattern throughout a lot of other models; access/return an attribute or association based on some conditions (otherwise returns nil?). like i feel like i see this a lot in the Flight model in augury, etc. and because this is such a simple example i think it makes a lot of sense.

File: app/models/transcript.rb [hunk 2]
```diff
@@ -114,4 +116,10 @@ def retry!
   def _retry=(_val)
     retry!
   end
+
+  # mime type required for rss - not necessarily the Porter detected mime_type we store
+  # https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#attributes
+  def rss_mime_type
+    MIME_TYPES[format&.to_sym]
```
Comment (radical-ube) [inline app/models/transcript.rb:123]: just thinking through validation logic for a second for myself. `format` must be present but `mime_type` could be blank (because that's only set from what Porter returns, if anything). and because `format` must always be present, then `rss_mime_type` should always be present; this would only return nil if `format` was blank. (and i guess, if `format` was not a matching key value for `MIME_TYPES`). ok, so this makes sense to me.

File: app/views/podcasts/show.rss.builder [hunk 3]
```diff
@@ -159,10 +159,10 @@ xml.rss "xmlns:atom" => "http://www.w3.org/2005/Atom",
               url: ep.enclosure_url(@feed))
           end
 
-          if ep.transcript?
+          if ep.ready_transcript
```
Comment (radical-ube) [inline app/views/podcasts/show.rss.builder:162]: ok, and then this conditional makes more sense now; not only does the transcript have to be present, but the episode status has to be complete (and therefore, valid transcript is present?). and within the conditional, we're only using what is available because of the conditional; we know that `ready_transcript` is not nil because we've already entered the conditional for it, so we should not encounter nil method errors while inside the conditional. so this solves the core issue of the bug.

**Review by radical-ube — APPROVED** [review]
looks good to me

File: app/views/podcasts/show.rss.builder (hunk 3 above)
Comment (cavis) [reply app/views/podcasts/show.rss.builder:162]: > but the episode status has to be complete

Close - the _transcript_ status has to be complete.  (But you probably meant that anyways).

**Comment by cavis** [comment]
Thanks @radical-ube !
