### PR TITLE
Import fixes

### LINKED ISSUE #1007: Handle invalid urls on import, if all they lack is a scheme
Had an import fail b/c the `<link/>` was a url, but missing the "https://" protocol

### LINKED ISSUE #1189: Support more podcast 2.0 tags on import
e.g. https://feeds.transistor.fm/never-post

They have podcast:transcript and podcast:guid tags, which we have now too, but I don't think we set on import?
https://github.com/PRX/feeder.prx.org/blob/main/app/models/imports/podcast_rss_import.rb
https://github.com/PRX/feeder.prx.org/blob/main/app/models/imports/episode_rss_import.rb

### PR DESCRIPTION
**Pull request by kookster**
- [x] Map podcast:guid
- [x] Map podcast:funding 
- [x] Respect podcast:locked
- [x] Try to fix urls w/o a scheme

fixes #1189
fixes #1007

### CODE REVIEW

File: app/models/concerns/import_utils.rb [hunk 1]
```diff
@@ -92,6 +92,32 @@ def clean_string(str)
     str.strip
   end
 
+  def clean_yes_no(str)
+    ["yes", "true", "1"].include?((clean_string(str) || "").downcase)
+  end
+
+  def clean_url(url)
```
Comment (cavis) [inline app/models/concerns/import_utils.rb:99]: +10... these have given us issues from time to time!

File: app/models/imports/podcast_rss_import.rb [hunk 2]
```diff
@@ -73,6 +73,10 @@ def validate_rss
       self.feed_episode_count = feed.entries.count
       channel
       first_entry
+
+      if clean_yes_no(channel[:podcast_locked])
```
Comment (cavis) [inline app/models/imports/podcast_rss_import.rb:77]: Nice to respect this tag!

**Review by cavis — APPROVED** [review]
:+2: some nice additions/improvements!
