### PR TITLE
Validate enclosure prefixes

### LINKED ISSUE #315: Check feed and enclosures working
We had an incident where a bad enclosure prefix made all downloads fail.
It wasn't detected for a couple of days.
Wondering if, like the feed monitoring we do for some shows with newrelic, we could build an enclosure and feed monitor to make sure they return rss and mp3s?

### PR DESCRIPTION
**Pull request by cavis**
Closes #315.

### CODE REVIEW

File: app/models/feed.rb [hunk 1]
```diff
@@ -51,7 +51,7 @@ class Feed < ApplicationRecord
   validates :episode_offset_seconds, numericality: {equal_to: 0}, allow_nil: true, if: :default?
   validates :url, http_url: true
   validates :new_feed_url, http_url: true
-  validates :enclosure_prefix, http_url: true
+  validates :enclosure_prefix, http_url: true, redirect_prefix: {max_jumps: 6}, allow_blank: true
```
Comment (kookster) [inline app/models/feed.rb:54]: 6 seems right - looking for a reference on what limit to impose - 

"Maximum 4 Prefix URLs!"
https://help.prx.org/hc/en-us/articles/30939698275611-How-to-add-and-remove-enclosure-prefix-URLS-in-Dovetail

"Libsyn’s system, therefore, will limit you to adding 3 URL prepends to your show’s file URLs."
https://help.libsynsupport.com/hc/en-us/articles/360041220231-Adding-a-URL-Prepend-or-Prefix-to-Your-Show

File: app/models/validators/redirect_prefix_validator.rb [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+  private
+
+  def head_request(uri_str, jumps = 0)
+    uri = URI.parse(uri_str)
+    http = Net::HTTP.new(uri.host, uri.port)
+    http.use_ssl = true if uri.scheme == "https"
+    req = Net::HTTP::Head.new(uri)
+    req["User-Agent"] = TEST_AGENT
+    res = http.request(req)
```
Comment (kookster) [inline app/models/validators/redirect_prefix_validator.rb:31]: Do we need a timeout?

File: test/models/validators/redirect_prefix_validator_test.rb [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+  it "validates too many redirects" do
+    one = "https://one.com/track/two.com/redirect.mp3/three.com/123456/dovetail.prxu.org/zero.mp3"
+    two = "https://two.com/redirect.mp3/three.com/123456/dovetail.prxu.org/zero.mp3"
+    three = "https://three.com/123456/dovetail.prxu.org/zero.mp3"
+    four = "https://dovetail.prxu.org/zero.mp3"
+
+    r1 = stub_request(:head, one).to_return(status: 302, headers: {location: two})
+    r2 = stub_request(:head, two).to_return(status: 301, headers: {location: three})
+    r3 = stub_request(:head, three).to_return(status: 302, headers: {location: four})
+    r4 = stub_request(:head, four).to_return(status: 200)
```
Comment (kookster) [inline test/models/validators/redirect_prefix_validator_test.rb:84]: clever use of stubs

**Review by kookster — APPROVED** [review]
lgtm!

File: app/models/validators/redirect_prefix_validator.rb (hunk 2 above)
Comment (cavis) [reply app/models/validators/redirect_prefix_validator.rb:31]: Hmm... do these not have a default?  Will check and add one if I need it.

**Review by svevang — COMMENTED** [review]
Looks good!
