### PR TITLE
Set empty link after save

### LINKED ISSUE #836: New podcasts get a bad default Homepage Link
When you create a new Podcast in feeder, and leave the Homepage Link blank, you end up with something like:

```
https://play.staging.prx.tech/listen?uf=https%3A%2F%2Ff-staging.prxu.org%2F%2Ffeed-rss.xml
```

That f-staging feed url is incorrect.  I'm guessing because this is being set before saving, there is no podcast id to put in there.

Fixitfixitfixit

### PR DESCRIPTION
**Pull request by radical-ube**
resolves #836

### CODE REVIEW

File: app/models/podcast.rb [hunk 1]
```diff
@@ -66,7 +67,12 @@ def self.release!(options = {})
 
   def set_defaults
     self.explicit ||= "false"
-    self.link ||= embed_player_landing_url(self)
+  end
+
+  def set_empty_link
+    if link.nil?
```
Comment (radical-ube) [inline app/models/podcast.rb:73]: this should only update `link` if it's still blank after saving, whether it's a new podcast or updating an existing one.

Comment (cavis) [reply app/models/podcast.rb:73]: Minor nitpick: I might use `.blank?` here, to catch empty strings `""` as well?  Just in case the web forms submitted a blank string.

**Review by cavis — APPROVED** [review]
One minor nitpick, but this feels like the right solution.
